ALTER DATABASE DB1 MODIFY FILEGROUP USR1 NAME = G5;

ALTER DATABASE DB1
	ADD FILE ( NAME = DB1_ONE, FILENAME='H:\SQL\1\DB1_TWO.NDF'),
			( NAME = DB_3, FILENAME = 'H:\SQL\1\DB_3.NDF'),
			(NAME = DB1_LOG2,  FILENAME = 'H:\SQL\1\DB1_LOG2.LDF')
		TO FILEGROUP G5
	GO